- name: Terminate ec2 instances
  ec2_instance:
    state: absent
    region: "{{ ec2_cluster.region }}"
    filters:
      tag:name: "{{ ec2_cluster.instance_tag }}"
  delegate_to: localhost
  run_once: true

- name: Cleanup ssh config file
  file:
    state: absent
    path: "{{ ec2_cluster.ssh_config_path }}"
  delegate_to: localhost
  run_once: true
