# registered ssh key to use. Use you default id_rsa.pub or modify the code
aws_ssh_key: areshytko
ami_id: ami-0163b0951ed4a6b22 # Deep Learning Base AMI (Ubuntu 18.04) Version 23.0
# ami_id: ami-061aaaac62de85935 # Deep Learning AMI (Ubuntu 18.04) Version 28.1
instance_count: 3
instance_type: g4dn.xlarge
region: eu-central-1
zone: eu-central-1b
# VPC to run EC2 instances in (most of the time fill id of default VPC here)
vpc_id: vpc-b53afadf
# tag to identify instances for cleanup
instance_tag: dl-experiment

python:
  version: 3.6
  virtualenv: /home/ubuntu/.venv
